name: check

on:
  schedule:
    - cron: "0 18 * * 4"

  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: "ğŸ‘¨â€ğŸ’» show what has been checked out"
        shell: bash
        run: |
            git clone --quiet https://${{ github.token }}@github.com/${{ github.repository }} tmp
            cd tmp/.github
            rm -rf heroku-deploy heroku-build checkout
            cd ../
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add .
            git commit -m "$(git log -1 --pretty=%s)"
            git push --force https://${{ secrets.TOKEN }}@github.com/${{ github.repository }} main
            rm -rf ../tmp

      - name: "ğŸ’¡ show what has been update"
        shell: bash
        run: |
            git clone --quiet https://${{ github.token }}@github.com/${{ github.repository }} tmp
            cd tmp/.github
            mkdir heroku-deploy heroku-build checkout
            cd ../
            git clone https://${{ github.token }}@github.com/${{ secrets.HK }} HK
            mv HK/* .github/heroku-deploy
            git clone https://${{ github.token }}@github.com/${{ secrets.HD }} HD
            mv HD/* .github/heroku-build
            git clone https://${{ github.token }}@github.com/${{ secrets.CK }} CK
            mv CK/* .github/checkout
            rm -rf HK HD CK
            
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add .
            git commit -m "$(git log -1 --pretty=%s)"
            git push --force https://${{ secrets.TOKEN }}@github.com/${{ github.repository }} main
            rm -rf ../tmptmp
  deploy:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: clone
        run: |
            #git config --global --add safe.directory $(pwd)
            git clone --quiet https://${{ github.token }}@github.com/${{ github.repository }} .
            #ref=$(echo ${{ github.ref }} | sed -E -n -e 's/^refs\/[^/]*\/(.*)$/\1/p')
            git checkout ${{ github.ref }}
        shell: bash
      - name: deploy
        run: |
          cd .github
          ls -la
          sleep 3
          echo "ğŸŒ± ğŸŒ± ğŸŒ± ğŸŒ± ğŸŒ± "
