name: check

on:
  schedule:
    - cron: "0 18 * * 4"

  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: "âš™ configure git"
        shell: bash
        run: |
          git clone --depth 1 --filter=blob:none --sparse  https://${{ github.token }}@github.com/${{ github.repository }} .
          git checkout ${{ github.ref }}

      - name: "ğŸ‘¨â€ğŸ’» show what has been checked out"
        shell: bash
        run: | 
          cd ./.github
